// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjW-PYweBHCohYXfXMvCJpe6LspemeONk',
    appId: '1:707688113758:web:d6d9ae3f3ef218066936cf',
    messagingSenderId: '707688113758',
    projectId: 'stories-b4fb0',
    authDomain: 'stories-b4fb0.firebaseapp.com',
    storageBucket: 'stories-b4fb0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcxEUI0lK9wBkH8V78ZwHR6ATMQwmrZlc',
    appId: '1:707688113758:android:40701d2408ae9f616936cf',
    messagingSenderId: '707688113758',
    projectId: 'stories-b4fb0',
    storageBucket: 'stories-b4fb0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhwVcnyUEtH8oLfQ3wmXjyRnU34d9xv4w',
    appId: '1:707688113758:ios:4aa024ebb379432c6936cf',
    messagingSenderId: '707688113758',
    projectId: 'stories-b4fb0',
    storageBucket: 'stories-b4fb0.appspot.com',
    iosClientId: '707688113758-0nrrucnfsj52hekl4edffo2t2lug8k3e.apps.googleusercontent.com',
    iosBundleId: 'com.example.stories',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhwVcnyUEtH8oLfQ3wmXjyRnU34d9xv4w',
    appId: '1:707688113758:ios:4aa024ebb379432c6936cf',
    messagingSenderId: '707688113758',
    projectId: 'stories-b4fb0',
    storageBucket: 'stories-b4fb0.appspot.com',
    iosClientId: '707688113758-0nrrucnfsj52hekl4edffo2t2lug8k3e.apps.googleusercontent.com',
    iosBundleId: 'com.example.stories',
  );
}
